[package]
name = "magnusi-tech-server"
version = "0.5.3"
authors = ["Lukáš Hozda <luk.hozda@gmail.com>"]
build = "build.rs"

[dependencies]
light_pencil = "0.4.3"
lazy_static = "0.2.9"
comrak = "0.2.3"
ansi_term = "0.10.2"
serde = "^1.0.4"
serde_derive = "^1.0.4"
toml = "0.4.5"
